import {before,after,test} from 'node:test';import fs from 'node:fs';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {doc,setDoc,getDoc,updateDoc,deleteDoc,writeBatch,serverTimestamp} from 'firebase/firestore';
import {normalizeGecko,publicProjection} from '../src/core.mjs';import {SEED} from '../src/catalog-seed.mjs';
let env,a,b,anon,guest;
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-crestie-community',firestore:{rules:fs.readFileSync('firestore.rules','utf8')}});a=env.authenticatedContext('alice',{firebase:{sign_in_provider:'google.com'}}).firestore();b=env.authenticatedContext('bob',{firebase:{sign_in_provider:'google.com'}}).firestore();anon=env.authenticatedContext('visitor',{firebase:{sign_in_provider:'anonymous'}}).firestore();guest=env.unauthenticatedContext().firestore();});
after(async()=>{await env?.cleanup();});
function priv(db,id){return doc(db,'users/alice/geckos/'+id);}function pub(db,id){return doc(db,'publicGeckos/alice__'+id);}
function g(id,extra={}){return {...normalizeGecko({id,name:'테스트 크레',...extra}),revision:1,updatedAt:serverTimestamp()};}
function publication(db,r){const batch=writeBatch(db);batch.set(priv(db,r.id),r);batch.set(pub(db,r.id),{...publicProjection(r,'alice'),updatedAt:serverTimestamp()});return batch;}
test('Google owner only can access private data',async()=>{await assertSucceeds(setDoc(priv(a,'private'),g('private')));await assertSucceeds(getDoc(priv(a,'private')));for(const client of [b,anon,guest])await assertFails(getDoc(priv(client,'private')));await assertFails(setDoc(doc(anon,'users/visitor/geckos/g'),g('g')));await assertFails(setDoc(priv(b,'hijack'),g('hijack')));});
test('public projection readable by guests; source remains private',async()=>{await assertSucceeds(publication(a,g('shared',{isPublic:true,notes:'PRIVATE NOTE'})).commit());await assertSucceeds(getDoc(pub(guest,'shared')));await assertFails(getDoc(priv(b,'shared')));await assertFails(updateDoc(pub(b,'shared'),{name:'hijack'}));});
test('private field injection into public projection denied',async()=>{const batch=publication(a,g('leak',{isPublic:true}));batch.update(pub(a,'leak'),{notes:'secret'});await assertFails(batch.commit());});
test('unpublishing requires atomic deletion of projection',async()=>{await assertFails(updateDoc(priv(a,'shared'),{isPublic:false,revision:2,updatedAt:serverTimestamp()}));const batch=writeBatch(a);batch.update(priv(a,'shared'),{isPublic:false,revision:2,updatedAt:serverTimestamp()});batch.delete(pub(a,'shared'));await assertSucceeds(batch.commit());if((await getDoc(pub(guest,'shared'))).exists())throw Error('Projection remains');});
test('stale revision and forged projection denied',async()=>{await assertFails(updateDoc(priv(a,'private'),{name:'stale',revision:1,updatedAt:serverTimestamp()}));await assertFails(setDoc(pub(a,'forged'),{...publicProjection(g('forged',{isPublic:true}),'alice'),updatedAt:serverTimestamp()}));});
function morph(revision=1,deleted=false){return {...SEED[0],revision,deleted,editorId:'visitor',updatedAt:serverTimestamp()};}
function edit(db,row){const batch=writeBatch(db);batch.set(doc(db,'morphs/normal'),row);batch.set(doc(db,'morphs/normal/history/'+row.revision),row);return batch.commit();}
test('anonymous edits accepted only with immutable history',async()=>{await assertSucceeds(edit(anon,morph()));await assertSucceeds(getDoc(doc(guest,'morphs/normal')));await assertFails(updateDoc(doc(anon,'morphs/normal/history/1'),{name:'tampered'}));await assertFails(deleteDoc(doc(anon,'morphs/normal/history/1')));});
test('catalog missing history and direct unauthenticated writes denied',async()=>{await assertFails(setDoc(doc(anon,'morphs/normal'),morph(2)));await assertFails(edit(guest,morph(2)));await assertFails(deleteDoc(doc(anon,'morphs/normal')));});
test('anonymous deletion and restoration are revisioned',async()=>{await assertSucceeds(edit(anon,morph(2,true)));await assertSucceeds(edit(anon,{...morph(3),name:'복원한 노멀'}));await assertSucceeds(getDoc(doc(guest,'morphs/normal/history/2')));});
test('growth belongs to Google owner and references own gecko',async()=>{const row={id:'r',geckoId:'private',date:'2026-09-22',weight:10,length:8,condition:'좋음',note:'PRIVATE',revision:1,updatedAt:serverTimestamp()};await assertSucceeds(setDoc(doc(a,'users/alice/growth/r'),row));await assertFails(getDoc(doc(b,'users/alice/growth/r')));await assertFails(setDoc(doc(a,'users/alice/growth/bad'),{...row,id:'bad',geckoId:'not-owned'}));});
