import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';import fs from 'node:fs/promises';import {pathToFileURL} from 'node:url';
const root=new URL('../',import.meta.url);
test('seven-view UI supports private creation, growth, pedigree, shared breeding and anonymous catalog editing',async()=>{
 const dom=new JSDOM(await fs.readFile(new URL('index.html',root),'utf8'),{url:'http://localhost'});
 const old={document:globalThis.document,FormData:globalThis.FormData,confirm:globalThis.confirm,setTimeout:globalThis.setTimeout,clearTimeout:globalThis.clearTimeout};
 const timers=new Set();globalThis.setTimeout=(fn,ms,...args)=>{const t=old.setTimeout(fn,ms,...args);timers.add(t);return t;};globalThis.clearTimeout=t=>{timers.delete(t);old.clearTimeout(t);};
 globalThis.document=dom.window.document;globalThis.FormData=dom.window.FormData;globalThis.confirm=()=>true;
 dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};
 const original=await fs.readFile(new URL('src/app.mjs',root),'utf8');
 const temp=new URL('src/.ui-test-app.mjs',root),mock=new URL('src/.ui-test-store.mjs',root);
 await fs.writeFile(mock,`export const chatUser=()=>null;export async function ensureVisitor(){}export const configured=true;const profileCallbacks={};const profiles={bob:{nickname:'크레집사'}};export function watchProfile(uid,cb){profileCallbacks[uid]=cb;cb(profiles[uid]||null);return()=>{delete profileCallbacks[uid];};}export async function saveNickname(nickname){profiles.alice={nickname:nickname.trim()};profileCallbacks.alice?.(profiles.alice);}const callbacks={};let user=null,auth;export const rows={geckos:[],growth:[],pairings:[]};export async function connect(){} export const friendlyError=e=>e.message;export function watchAuth(cb){auth=cb;cb(user);}export async function login(){user={uid:'alice',displayName:'테스트'};auth(user);}export async function logout(){user=null;auth(null);}export function watchOwn(k,cb){callbacks[k]=cb;cb(rows[k]);return()=>{delete callbacks[k];};}export function watchCatalog(cb){callbacks.catalog=cb;cb([]);}export function watchPublic(cb){cb([{publicId:'bob__b',ownerId:'bob',geckoId:'b',name:'공개 크레',morph:'노멀',sex:'male',photos:[],customTraits:[],genetics:{lilly:'normal',axanthic:'clear',cappuccino:'normal'}}]);return()=>{};}export async function getPublic(){return {publicId:'bob__b',ownerId:'bob',geckoId:'b',name:'공개 크레',sex:'male',photos:[],customTraits:[],genetics:{lilly:'normal',axanthic:'clear',cappuccino:'normal'}};}export async function saveRecord(k,r,rev){const at=rows[k].findIndex(x=>x.id===r.id);const next={...r,revision:rev+1};if(at<0)rows[k].push(next);else rows[k][at]=next;callbacks[k]?.(rows[k]);}export async function removeRecord(k,r){rows[k]=rows[k].filter(x=>x.id!==r.id);callbacks[k]?.(rows[k]);}export const morphEdits=[];export async function saveMorph(m,rev){morphEdits.push({...m,revision:rev+1});callbacks.catalog(morphEdits);}export async function morphHistory(){return morphEdits;}`);
 await fs.writeFile(temp,original.replace("'./firebase.mjs'","'./.ui-test-store.mjs'"));
 const q=s=>document.querySelector(s),click=s=>{assert(q(s),'Missing '+s);q(s).click();},flush=()=>new Promise(r=>setTimeout(r,0));
 try{await import(pathToFileURL(temp.pathname));const data=await import(pathToFileURL(mock.pathname));
 assert.equal(document.querySelectorAll('[data-view]').length,7);assert(!document.body.textContent.includes('가계부'));
 click('[data-view=morphs]');assert.equal(document.querySelectorAll('.morph-card').length,46);
 click('[data-action=add-morph]');q('[name=name]').value='테스트 모프';q('[name=look]').value='테스트 설명';q('[name=inheritance]').value='codominant';q('#editor form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await flush();assert.equal(data.morphEdits[0].inheritance,'codominant');assert.equal(document.querySelectorAll('.morph-card').length,47);
 click('#authArea [data-action=login]');await flush();assert(q('[name=nickname]'));q('[name=nickname]').value='나의닉네임';q('#editor form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await flush();assert(q('#authArea').textContent.includes('나의닉네임'));click('[data-view=geckos]');click('[data-action=public]');assert(q('#content').textContent.includes('주인 · 크레집사'));click('[data-action=mine]');click('[data-action=add-gecko]');q('[name=name]').value='내 크레';q('[name=sex]').value='female';assert(!q('[name=lilly]'));assert(!q('[name=axanthic]'));assert(!q('[name=customTraits]'));click('[data-trait="릴리화이트"]');q('#editor form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await flush();assert.equal(data.rows.geckos.length,1);assert.equal(data.rows.geckos[0].isPublic,false);
 click('[data-view=growth]');click('[data-action=add-growth]');q('[name=weight]').value='12';q('#editor form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await flush();assert.equal(data.rows.growth[0].weight,12);
 click('[data-view=pedigree]');assert(q('.pedigree-board svg'));
 click('[data-view=genetics]');click('[data-action=calculate]');await flush();assert(q('#genResult').textContent.includes('50%'));assert(q('#genResult').textContent.includes('릴리화이트'));
 click('#authArea [data-action=logout]');await flush();click('[data-view=geckos]');assert(!q('#content').textContent.includes('내 크레'));
 }finally{for(const t of timers)old.clearTimeout(t);await fs.unlink(temp);await fs.unlink(mock);dom.window.close();Object.assign(globalThis,old);}
});
