import {mountChat} from './chat-ui.mjs';
import {EXTRA_TRAITS,initialTraits,traitsToGenes,simulateTraits} from './trait-genetics.mjs';
import {openLegacyImport} from './legacy-import.mjs';
import {SEED} from './catalog-seed.mjs';
import {GROUPS,INHERITANCE,GENES,esc,id,splitTraits,sexLabel,dateNow,pct,normalizeGecko,validateGecko,ancestors,relation,offspring,offspringName,mergeCatalog,filterMorphs} from './core.mjs';
import * as store from './firebase.mjs';
const $=s=>document.querySelector(s), content=$('#content'),dialog=$('#editor');
const state={user:null,geckos:[],growth:[],pairings:[],public:[],catalog:[...SEED],ready:false,ownLoaded:false};
const meta={chat:['채팅방','함께 이야기하고, 관심 있는 크레의 주인과 대화하세요.'],dashboard:['대시보드','크레와 함께 쌓아가는 기록'],geckos:['개체 관리','나의 개체를 기록하고, 공개한 크레를 만나보세요.'],growth:['성장 기록','날짜별 체중과 전장 변화를 함께 기록합니다.'],pedigree:['교배 · 가계도','부모와 자손의 관계를 한눈에 확인하세요.'],morphs:['모프 도감','누구나 함께 다듬는 크레 모프 안내'],genetics:['유전 · 교배 예상','나의 개체와 공개된 개체로 자손을 예상합니다.']};
let chatCleanup=null,chatRoom='',chatUid=null;
let view='dashboard',tab='mine',morphQ='',morphGroup='',showDeleted=false,geckoQ='',growthFocus='',choiceA='',choiceB='',unsub=[],authEpoch=0,calcEpoch=0,publicLimit=200,stopPublic=null;
const profiles=new Map(),profileStops=new Map();let nicknamePrompted=false;
const ownerNickname=uid=>profiles.get(uid)?.nickname||'닉네임 미설정';
const mine=()=>state.geckos.filter(g=>!g.deleted),gecko=gid=>state.geckos.find(g=>g.id===gid),name=gid=>gecko(gid)?.name||'미등록',living=()=>new Set(mine().map(g=>g.id));
const fmt=v=>v||'—', stamp=v=>v?.toDate? v.toDate().toLocaleString('ko-KR'):'초기 도감';
const empty=(a,b='')=>`<div class="empty"><b>${esc(a)}</b><span>${esc(b)}</span></div>`;
const btn=(action,label,extra='',primary=false)=>`<button type="button" class="btn ${primary?'primary':'secondary'}" data-action="${action}" ${extra}>${label}</button>`;
const options=(values,selected='')=>Object.entries(values).map(([k,v])=>`<option value="${esc(k)}" ${k===selected?'selected':''}>${esc(v)}</option>`).join('');
const field=(label,key,value='',type='text',extra='')=>`<label>${label}<input name="${key}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const area=(label,key,value='',max=2000)=>`<label>${label}<textarea name="${key}" rows="3" maxlength="${max}">${esc(value)}</textarea></label>`;
const select=(label,key,values,value='')=>`<label>${label}<select name="${key}">${options(values,value)}</select></label>`;
const ownOptions=(blank=true,exclude='')=>Object.fromEntries([...(blank?[['','미등록']]:[]),...mine().filter(g=>g.id!==exclude).map(g=>[g.id,g.name])]);
function toast(text){$('#status').textContent=text;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#status').textContent='',6500);}
function setView(v){view=v;render();}
function render(){
 if(view!=='chat'&&chatCleanup){chatCleanup();chatCleanup=null;}
 $('#viewTitle').textContent=meta[view][0];$('#viewSubtitle').textContent=meta[view][1];
 document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 ({chat:renderChat,dashboard:renderDashboard,geckos:renderGeckos,growth:renderGrowth,pedigree:renderPedigree,morphs:renderMorphs,genetics:renderGenetics})[view]();
}
function authUI(){const u=state.user;$('#authArea').innerHTML=u?`<span class="account-name">${esc(profiles.get(u.uid)?.nickname||'내 계정')}</span>${btn('nickname',profiles.get(u.uid)?.nickname?'닉네임 변경':'닉네임 설정')}${btn('logout','로그아웃')}`:btn('login','Google로 로그인','',true);}
function loginWall(){return `<div class="card empty-login"><h2>나만의 크레 기록을 시작하세요.</h2><p>Google 계정으로 로그인하면 내 개체와 성장·교배 기록을<br>여러 기기에서 이어서 관리할 수 있어요.</p>${btn('login','Google로 로그인','',true)}<p class="foot-meta">모프 도감과 공개 개체는 로그인 없이 볼 수 있습니다.</p></div>`;}
function needOwn(){if(!state.user){content.innerHTML=loginWall();return false;}if(!state.ownLoaded){content.innerHTML='<div class="loading">내 기록을 불러오는 중…</div>';return false;}return true;}
function renderDashboard(){
 const gs=mine(),ids=living(),growth=state.growth.filter(r=>ids.has(r.geckoId)),pairs=state.pairings.filter(p=>ids.has(p.aId)&&ids.has(p.bId));
 content.innerHTML=`<div class="card welcome"><div><h2>${state.user?'오늘도 크레와 함께':'각자의 크레, 함께 쌓는 이야기'}</h2><p>${state.user?'나의 기록은 비공개로 보관하고, 원하는 개체만 공개해 보세요.':'성장과 혈통은 나만의 공간에, 모프 지식은 모두의 도감에.'}</p></div>${state.user?btn('add-gecko','＋ 개체 등록','',true):btn('login','Google로 시작하기','',true)}</div><div class="grid cols-4">${[['내 개체',gs.length],['내 공개 개체',gs.filter(g=>g.isPublic).length],['성장 기록',growth.length],['교배 기록',pairs.length]].map(([l,n])=>`<div class="card stat-card"><div class="stat-label">${l}</div><div class="stat-value">${n}</div></div>`).join('')}</div><div class="grid cols-2 section-gap"><div class="card pad"><h2>최근 성장 기록</h2>${growth.length?`<div class="list">${[...growth].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(r=>`<div class="list-item"><div class="list-main"><b>${esc(name(r.geckoId))}</b><span>${esc(r.date)}</span></div><span class="badge">${r.weight} g</span></div>`).join('')}</div>`:empty('아직 성장 기록이 없어요.')}</div><div class="card pad"><h2>함께 둘러보기</h2><p class="muted">모프 도감의 ${state.catalog.filter(m=>!m.deleted).length}개 항목을 살펴보고, 공개된 개체로 교배를 예상해 보세요.</p><div class="toolbar">${btn('go-public','공개 개체 보기')}${btn('go-morphs','모프 도감')}${btn('go-genetics','교배 예상')}</div></div></div>`;
}
function card(g,own){const key=own?g.id:g.publicId;return `<article class="card gecko-card">${g.photos?.[0]?`<img class="gecko-cover" src="${esc(g.photos[0])}" alt="${esc(g.name)}" loading="lazy">`:'<div class="gecko-cover empty-photo">등록된 사진이 없어요</div>'}<div class="gecko-body"><div class="gecko-meta"><span class="badge">${sexLabel(g.sex)}</span><span class="badge ${own&&!g.isPublic?'private-label':'public-label'}">${own?(g.isPublic?'공개':'나만 보기'):'공개 개체'}</span></div><h3>${esc(g.name)}</h3>${own?'':`<p class="owner-nickname" data-owner-id="${esc(g.ownerId)}">주인 · ${esc(ownerNickname(g.ownerId))}</p>`}<div class="muted">${esc(g.morph||'모프 미입력')}</div><div class="tag-line">${(g.customTraits||[]).map(t=>`<span class="morph-tag">${esc(t)}</span>`).join('')}</div><div class="actions">${!own?btn('dm-public','주인과 대화',`data-id="${esc(g.publicId)}"`):''}${btn(own?'edit-gecko':'detail-public',own?'관리 · 수정':'상세 보기',`data-id="${esc(key)}"`)}${btn('use-genetics','교배 예상',`data-id="${esc((own?'own:':'public:')+key)}"`)}</div></div></article>`;}
function renderGeckos(){content.innerHTML=`<div class="community-tabs">${btn('mine','내 개체',`aria-pressed="${tab==='mine'}"`,tab==='mine')}${btn('public','공개 개체',`aria-pressed="${tab==='public'}"`,tab==='public')}</div><div id="geckoPanel"></div>`;
 const panel=$('#geckoPanel');if(tab==='mine'&&!state.user){panel.innerHTML=loginWall();return;}
 if(tab==='mine'&&!state.ownLoaded){panel.innerHTML='<p class="loading">내 기록을 불러오는 중…</p>';return;}
 const rows=(tab==='mine'?mine():state.public).filter(g=>[g.name,g.morph,...(g.customTraits||[])].join(' ').toLowerCase().includes(geckoQ.toLowerCase()));
 panel.innerHTML=`<div class="toolbar section-head"><label>이름 · 모프 검색<input id="geckoSearch" type="search" value="${esc(geckoQ)}" placeholder="이름이나 모프를 입력하세요"></label>${tab==='mine'?btn('import-legacy','이전 기록 가져오기')+btn('add-gecko','＋ 개체 등록','',true):'<p class="muted">공개를 허용한 개체만 표시됩니다.</p>'}</div><div id="geckoCards" class="gecko-grid">${rows.map(g=>card(g,tab==='mine')).join('')||empty('표시할 개체가 없습니다.')}</div>${tab==='public'&&state.public.length===publicLimit?'<div class="section-gap">'+btn('more-public','공개 개체 더 불러오기')+'</div>':''}`;
 $('#geckoSearch').oninput=e=>{geckoQ=e.target.value;const found=(tab==='mine'?mine():state.public).filter(g=>[g.name,g.morph,...(g.customTraits||[])].join(' ').toLowerCase().includes(geckoQ.toLowerCase()));$('#geckoCards').innerHTML=found.map(g=>card(g,tab==='mine')).join('')||empty('검색 결과가 없습니다.');};
}
function openForm(title,body,onSubmit){
 dialog.innerHTML=`<form class="modal-card"><div class="modal-head"><h2>${esc(title)}</h2><button type="button" class="icon-btn" data-close aria-label="닫기">×</button></div>${body}<div class="form-error" role="alert"></div><div class="modal-actions"><button type="button" class="btn secondary" data-close>취소</button><button type="submit" class="btn primary">저장</button></div></form>`;
 dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,submit=form.querySelector('[type=submit]');submit.disabled=true;form.querySelector('.form-error').textContent='';try{await onSubmit(new FormData(form),form);dialog.close();toast('저장했습니다.');}catch(err){form.querySelector('.form-error').textContent=store.friendlyError(err);}finally{submit.disabled=false;}};
 dialog.showModal();
}
function requireUser(){if(!state.user){toast('개체를 관리하려면 Google로 로그인해 주세요.');return false;}return true;}
async function compress(file){
 if(!file.type.startsWith('image/'))throw Error('이미지 파일을 선택하세요.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,900/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
 for(const quality of [.8,.65,.5,.35,.2]){const result=canvas.toDataURL('image/jpeg',quality);if(result.length<=180000)return result;}throw Error('사진 용량이 큽니다. 크기를 줄인 사진을 선택하세요.');
}
function editGecko(gid){
 if(!requireUser())return;const original=gid?gecko(gid):null,g=normalizeGecko(original||{}),epoch=authEpoch;let photos=[...g.photos],photoBusy=false;
 const selected=new Set(initialTraits(g,state.catalog));
 const traitNames=[...new Set([...state.catalog.filter(m=>!m.deleted).map(m=>m.name),...EXTRA_TRAITS.map(([name])=>name),...selected])];
 openForm(original?'개체 정보 수정':'개체 등록',`<div class="form-grid two">${field('이름','name',g.name,'text','required maxlength="80"')}${field('표시 모프','morph',g.morph,'text','maxlength="200"')}${select('성별','sex',{unknown:'미확인',male:'수컷',female:'암컷'},g.sex)}${field('부화일','hatchDate',g.hatchDate,'date')}${field('입양일','acquiredDate',g.acquiredDate,'date')}${field('브리더 · 출처 (비공개)','breeder',g.breeder,'text','maxlength="200"')}${select('부모 1','parent1Id',ownOptions(true,g.id),g.parent1Id)}${select('부모 2','parent2Id',ownOptions(true,g.id),g.parent2Id)}</div><label class="check"><input name="isPublic" type="checkbox" ${g.isPublic?'checked':''}><span>이 개체를 다른 사람에게 공개합니다.<br><span class="help">이름·모프·성별·부화일·사진·선택한 특징·유전 정보가 공개되며 다른 사람의 교배 예상에 사용됩니다. 개인 메모·성장 기록·부모 연결·분양 출처는 공개하지 않습니다.</span></span></label>${field('분양 · 혈통 표기 (비공개)','breederNotation',g.breederNotation,'text','maxlength="500"')}<section class="morph-picker"><h3>도감에서 특징 선택</h3><p class="help">해당하는 특징을 모두 선택하세요. 릴리아잔틱 같은 조합은 교배 예상에 자동 연결됩니다. 헷·슈퍼·없음 확인도 여기서 선택합니다. 선택하지 않은 유전자는 미확인으로 유지됩니다.</p><input id="traitSearch" type="search" aria-label="특징 검색" placeholder="모프 · 헷 · 특징 검색"><div id="selectedTraits" class="tag-line"></div><div class="morph-picker-options">${traitNames.map(name=>`<button type="button" class="morph-choice" data-trait="${esc(name)}" aria-pressed="${selected.has(name)}">${esc(name)}</button>`).join('')}</div></section><section><h3>사진</h3><p class="help">최대 3장. 저장할 때 사진을 작은 JPEG로 압축합니다.</p><input id="photoInput" type="file" accept="image/*" multiple aria-label="사진 추가"><div id="photoStrip" class="photo-strip"></div></section>${area('개인 메모 (비공개)','notes',g.notes,5000)}${original?btn('delete-in-editor','이 개체 삭제'):''}`,async data=>{
 if(epoch!==authEpoch)throw Error('계정이 변경되었습니다.');if(photoBusy)throw Error('사진을 처리 중입니다. 잠시 후 저장하세요.');
 const next=normalizeGecko({...g,...Object.fromEntries(data),id:g.id,photos,isPublic:data.has('isPublic'),customTraits:[...selected],genetics:traitsToGenes([...selected],state.catalog)});validateGecko(next,mine());await store.saveRecord('geckos',next,g.revision);
 });
 const paintPhotos=()=>{$('#photoStrip').innerHTML=photos.map((p,i)=>`<div><img src="${p}" alt="사진 ${i+1}"><button type="button" class="btn ghost small" data-remove-photo="${i}">제외</button></div>`).join('');$('#photoStrip').querySelectorAll('[data-remove-photo]').forEach(b=>b.onclick=()=>{photos.splice(+b.dataset.removePhoto,1);paintPhotos();});};paintPhotos();
 $('#photoInput').onchange=async e=>{photoBusy=true;const input=e.target;input.disabled=true;try{if(photos.length+input.files.length>3)throw Error('사진은 3장까지 가능합니다.');const added=await Promise.all([...input.files].map(compress));photos.push(...added);paintPhotos();}catch(err){dialog.querySelector('.form-error').textContent=err.message;}finally{photoBusy=false;input.disabled=false;input.value='';}};
 const paintTraits=()=>{dialog.querySelectorAll('[data-trait]').forEach(b=>b.setAttribute('aria-pressed',String(selected.has(b.dataset.trait))));$('#selectedTraits').innerHTML=[...selected].map(t=>`<span class="morph-tag">${esc(t)}</span>`).join('')||'<span class="help">선택한 특징이 없습니다.</span>';};paintTraits();
 dialog.querySelectorAll('[data-trait]').forEach(b=>b.onclick=()=>{selected.has(b.dataset.trait)?selected.delete(b.dataset.trait):selected.add(b.dataset.trait);paintTraits();});
 $('#traitSearch').oninput=e=>{const q=e.target.value.trim().toLowerCase();dialog.querySelectorAll('[data-trait]').forEach(b=>b.hidden=!b.dataset.trait.toLowerCase().includes(q));};
 if(original)dialog.querySelector('[data-action=delete-in-editor]').onclick=async()=>{if(!confirm('이 개체를 목록에서 삭제하고 공개도 해제할까요?'))return;try{await store.removeRecord('geckos',g);dialog.close();toast('개체를 삭제했습니다.');}catch(e){dialog.querySelector('.form-error').textContent=store.friendlyError(e);}};
}
function renderGrowth(){
 if(!needOwn())return;const gs=mine();if(!gs.some(g=>g.id===growthFocus))growthFocus=gs[0]?.id||'';const rows=state.growth.filter(r=>r.geckoId===growthFocus).sort((a,b)=>a.date.localeCompare(b.date));
 content.innerHTML=`<div class="card pad"><div class="section-head"><h2>성장 추이</h2>${btn('add-growth','＋ 성장 기록','',true)}</div>${gs.length?`<label>개체<select id="growthFocus">${options(ownOptions(false),growthFocus)}</select></label>${growthChart(rows)}`:empty('먼저 개체를 등록하세요.')}</div><div class="card growth-card">${rows.length?`<div class="table-wrap"><table><thead><tr><th>날짜</th><th>체중</th><th>전장</th><th>상태</th><th>메모</th><th>관리</th></tr></thead><tbody>${[...rows].reverse().map(r=>`<tr><td>${esc(r.date)}</td><td>${r.weight} g</td><td>${r.length||'—'} cm</td><td>${esc(r.condition)}</td><td>${esc(r.note)}</td><td><div class="table-actions">${btn('edit-growth','수정',`data-id="${esc(r.id)}"`)}${btn('delete-growth','삭제',`data-id="${esc(r.id)}"`)}</div></td></tr>`).join('')}</tbody></table></div>`:empty('성장 기록이 없습니다.')}</div>`;
 if($('#growthFocus'))$('#growthFocus').onchange=e=>{growthFocus=e.target.value;renderGrowth();};
}
function growthChart(rows){if(rows.length<2)return empty('기록이 2개 이상이면 체중 그래프가 표시됩니다.');const min=Math.min(...rows.map(r=>r.weight)),max=Math.max(...rows.map(r=>r.weight)),range=max-min||1,W=800,H=250;const start=Date.parse(rows[0].date),end=Date.parse(rows.at(-1).date);const x=(r,i)=>end===start?45+i*710/(rows.length-1):45+(Date.parse(r.date)-start)*710/(end-start),y=r=>205-(r.weight-min)*160/range;return `<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="날짜별 체중 그래프"><path d="M45 35V205H760" fill="none" stroke="#d5deeb"/><text x="4" y="42">${max} g</text><text x="4" y="205">${min} g</text><text x="45" y="238">${esc(rows[0].date)}</text><text x="675" y="238">${esc(rows.at(-1).date)}</text><path d="${rows.map((r,i)=>(i?'L':'M')+x(r,i)+' '+y(r)).join(' ')}" fill="none" stroke="#5b6ee1" stroke-width="3"/>${rows.map((r,i)=>`<circle cx="${x(r,i)}" cy="${y(r)}" r="4" fill="#5b6ee1"><title>${esc(r.date)} · ${r.weight} g</title></circle>`).join('')}</svg>`;}
function editGrowth(rid){if(!requireUser())return;if(!mine().length){toast('먼저 개체를 등록하세요.');return;}const r=state.growth.find(x=>x.id===rid)||{id:id(),geckoId:growthFocus||mine()[0].id,date:dateNow(),weight:'',length:'',condition:'좋음',note:'',revision:0};const epoch=authEpoch;
 openForm(rid?'성장 기록 수정':'성장 기록 추가',`${select('개체','geckoId',ownOptions(false),r.geckoId)}<div class="form-grid two">${field('날짜','date',r.date,'date','required')}${field('체중 (g)','weight',r.weight,'number','min="0" max="1000" step="0.01" required')}${field('전장 (cm, 선택)','length',r.length,'number','min="0" max="100" step="0.1"')}${select('상태','condition',{'좋음':'좋음','보통':'보통','관찰 필요':'관찰 필요'},r.condition)}</div>${area('메모','note',r.note)}`,async d=>{if(epoch!==authEpoch)throw Error('계정이 변경되었습니다.');const next={...Object.fromEntries(d),id:r.id,weight:+d.get('weight'),length:+d.get('length'),revision:r.revision};await store.saveRecord('growth',next,r.revision);growthFocus=next.geckoId;});
}
function renderPedigree(){if(!needOwn())return;const gs=mine(),ids=living(),pairs=state.pairings.filter(p=>ids.has(p.aId)&&ids.has(p.bId));content.innerHTML=`<div class="card pad"><div class="section-head"><div><h2>우리 크레 가계도</h2><p class="muted">개체 등록에서 부모를 지정하면 연결됩니다.</p></div>${btn('add-pair','＋ 교배 기록','',true)}</div><div class="pedigree-board">${pedigreeSvg(gs)}</div></div><div class="card section-gap">${pairs.length?`<div class="table-wrap"><table><thead><tr><th>개체 A</th><th>개체 B</th><th>관계</th><th>날짜</th><th>상태</th><th>메모</th><th>관리</th></tr></thead><tbody>${pairs.map(p=>`<tr><td>${esc(name(p.aId))}</td><td>${esc(name(p.bId))}</td><td>${esc(relation(gecko(p.aId),gecko(p.bId),gs))}</td><td>${esc(p.date)}</td><td>${esc(pairStates[p.status])}</td><td>${esc(p.note)}</td><td>${btn('edit-pair','수정',`data-id="${esc(p.id)}"`)}${btn('delete-pair','삭제',`data-id="${esc(p.id)}"`)}</td></tr>`).join('')}</tbody></table></div>`:empty('등록된 교배 기록이 없습니다.')}</div>`;}
function pedigreeSvg(gs){if(!gs.length)return empty('개체를 등록하면 가계도가 만들어집니다.');const memo=new Map();function level(g,seen=new Set()){if(memo.has(g.id))return memo.get(g.id);if(seen.has(g.id))return 0;seen.add(g.id);const ps=[g.parent1Id,g.parent2Id].map(p=>gs.find(x=>x.id===p)).filter(Boolean);const n=ps.length?1+Math.max(...ps.map(p=>level(p,new Set(seen)))):0;memo.set(g.id,n);return n;}const groups={};gs.forEach(g=>(groups[level(g)]??=[]).push(g));const width=Math.max(720,...Object.values(groups).map(a=>a.length*200+40)),height=(Math.max(...Object.keys(groups).map(Number))+1)*150+30,pos={};Object.entries(groups).forEach(([l,arr])=>arr.forEach((g,i)=>pos[g.id]={x:20+i*200,y:20+Number(l)*150}));return `<svg viewBox="0 0 ${width} ${height}" style="min-width:${width}px" role="img" aria-label="등록된 부모 관계 가계도">${gs.flatMap(g=>[g.parent1Id,g.parent2Id].filter(p=>pos[p]).map(p=>{const a=pos[p],b=pos[g.id];return `<path class="pedigree-edge" d="M${a.x+85} ${a.y+80} C${a.x+85} ${a.y+110} ${b.x+85} ${b.y-30} ${b.x+85} ${b.y}"/>`;})).join('')}${gs.map(g=>{const p=pos[g.id];return `<g class="pedigree-node" transform="translate(${p.x},${p.y})"><rect width="170" height="80" rx="12"/><text x="12" y="27">${esc(g.name.slice(0,12))}</text><text class="sub" x="12" y="48">${esc((g.morph||'모프 미입력').slice(0,17))}</text><text class="sub" x="12" y="66">${sexLabel(g.sex)}</text></g>`;}).join('')}</svg>`;}
const pairStates={planned:'계획',paired:'교배 진행',eggs:'산란 · 알',hatched:'부화 확인',closed:'종료'};
function editPair(rid){if(!requireUser())return;if(mine().length<2){toast('개체를 2마리 이상 등록하세요.');return;}const r=state.pairings.find(x=>x.id===rid)||{id:id(),aId:mine()[0].id,bId:mine()[1].id,date:dateNow(),status:'planned',note:'',revision:0},epoch=authEpoch;
 openForm(rid?'교배 기록 수정':'교배 기록 추가',`<div class="form-grid two">${select('개체 A','aId',ownOptions(false),r.aId)}${select('개체 B','bId',ownOptions(false),r.bId)}${field('날짜','date',r.date,'date','required')}${select('상태','status',pairStates,r.status)}</div><p class="help">미확인 성별은 후보로 선택할 수 있습니다. 실제 교배 기록은 내가 관리하는 개체끼리 연결합니다.</p>${area('메모','note',r.note)}`,async d=>{if(epoch!==authEpoch)throw Error('계정이 변경되었습니다.');if(d.get('aId')===d.get('bId'))throw Error('서로 다른 개체를 선택하세요.');const a=gecko(d.get('aId')),b=gecko(d.get('bId'));if(a.sex!=='unknown'&&a.sex===b.sex&&!confirm('같은 성별로 등록되어 있습니다. 기록을 저장할까요?'))throw Error('저장을 취소했습니다.');await store.saveRecord('pairings',{...Object.fromEntries(d),id:r.id,revision:r.revision},r.revision);});
}
function renderMorphs(){
 content.innerHTML=`<div class="morph-hero"><div><span class="morph-eyebrow">OPEN MORPH GUIDE</span><h2>함께 만드는<br>크레스티드 모프 도감</h2><p>기본 무늬부터 유전 조합까지.<br>로그인 없이 항목을 추가하고 내용을 다듬어 보세요.</p></div><div class="morph-total"><b>${state.catalog.filter(m=>!m.deleted).length}</b><span>모프 · 특징 안내</span></div></div><div class="card pad morph-tools"><div class="toolbar"><label>이름 · 특징 검색<input id="morphSearch" type="search" value="${esc(morphQ)}" placeholder="릴잔틱, 달마시안, Pinstripe"></label>${btn('add-morph','＋ 모프 추가','',true)}</div><div class="morph-filters">${[['','전체'],...Object.entries(GROUPS)].map(([key,label])=>`<button type="button" class="morph-filter" data-group="${key}" aria-pressed="${key===morphGroup}">${label}</button>`).join('')}</div><div class="toolbar section-gap"><label class="check"><input id="showDeleted" type="checkbox" ${showDeleted?'checked':''}>삭제된 항목 보기 · 복원</label></div><p class="catalog-warning">누구나 편집할 수 있는 공용 정보입니다. 유전 표기는 근거와 함께 기록해 주세요. ‘공우성’과 ‘불완전우성’은 다르며, 외형 명칭을 유전 형질로 자동 간주하지 않습니다.</p><p id="morphCount" aria-live="polite"></p></div><div id="morphGrid" class="morph-grid"></div>`;
 $('#morphSearch').oninput=e=>{morphQ=e.target.value;drawMorphCards();};$('#showDeleted').onchange=e=>{showDeleted=e.target.checked;drawMorphCards();};content.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{morphGroup=b.dataset.group;content.querySelectorAll('[data-group]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));drawMorphCards();});drawMorphCards();
}
function drawMorphCards(){const rows=filterMorphs(state.catalog,morphQ,morphGroup,showDeleted);$('#morphCount').textContent=`${rows.length}개 항목${showDeleted?' · 삭제됨':''}`;$('#morphGrid').innerHTML=rows.map(m=>`<article class="morph-card morph-${m.group}"><div class="morph-card-top"><span class="morph-category">${esc(GROUPS[m.group])}</span><span class="morph-index">${esc(m.en)}</span></div><h3>${esc(m.name)}</h3><div class="inheritance-line"><span class="inheritance">${esc(INHERITANCE[m.inheritance])}</span>${m.deleted?'<span class="badge warn">삭제됨</span>':''}</div><p>${esc(m.look)}</p><details><summary>상세 설명 · 근거</summary><p>${esc(m.note)}</p>${m.aliases?`<p>다른 표기: ${esc(m.aliases)}</p>`:''}${m.sources?`<p>참고 자료: ${esc(m.sources)}</p>`:''}<p class="foot-meta">${m.revision?'수정 '+m.revision+'회 · '+stamp(m.updatedAt):'초기 안내 · 46개 항목에서 시작'}</p></details><div class="morph-actions">${btn('edit-morph',m.deleted?'수정 · 복원':'수정',`data-id="${m.id}"`)}${!m.deleted?btn('delete-morph','삭제',`data-id="${m.id}"`):''}${btn('history-morph','이력',`data-id="${m.id}"`)}</div></article>`).join('')||empty('일치하는 항목이 없습니다.');}
function editMorph(mid,restore){
 const current=state.catalog.find(m=>m.id===mid),m=restore||current||{id:id(),name:'',en:'',group:'basic',look:'',note:'',aliases:'',sources:'',inheritance:'unknown',deleted:false,revision:0};
 openForm(current?'모프 수정'+(current.deleted?' · 복원':''):'모프 추가',`<p class="help">저장하면 모든 사람에게 반영됩니다. Google 로그인은 필요 없으며 변경 이력은 남습니다.</p><div class="form-grid two">${field('모프 이름','name',m.name,'text','required maxlength="80"')}${field('영문 이름','en',m.en,'text','maxlength="120"')}${select('분류','group',GROUPS,m.group)}${select('유전 방식','inheritance',INHERITANCE,m.inheritance)}</div>${area('특징 · 알아보는 방법','look',m.look,1500)}${area('상세 설명 · 유전 정보','note',m.note,2000)}${field('별칭','aliases',m.aliases,'text','maxlength="300"')}${area('참고 자료 · 출처','sources',m.sources,1500)}${current?.deleted?'<p class="notice">저장하면 삭제된 항목을 도감에 복원합니다.</p>':''}`,async d=>{await store.saveMorph({...m,...Object.fromEntries(d),deleted:false},current?.revision||0);});
}
async function deleteMorph(mid){const m=state.catalog.find(x=>x.id===mid);if(!confirm(`‘${m.name}’을 공용 도감에서 삭제할까요? 변경 이력에서 복원할 수 있습니다.`))return;await store.saveMorph({...m,deleted:true},m.revision);toast('항목을 삭제했습니다. 삭제된 항목 보기에서 복원할 수 있어요.');}
async function showHistory(mid){
 const m=state.catalog.find(x=>x.id===mid);const history=state.ready?await store.morphHistory(mid):[];const seed=SEED.find(x=>x.id===mid);const rows=[...history,...(seed?[seed]:[])];
 dialog.innerHTML=`<div class="modal-card"><div class="modal-head"><h2>${esc(m.name)} · 변경 이력</h2><button type="button" class="icon-btn" data-close aria-label="닫기">×</button></div><p class="help">최근 변경 30개와 최초 안내를 확인합니다. 복원도 새로운 수정으로 남습니다.</p>${rows.map((r,i)=>`<div class="history-row"><b>${r.revision?'버전 '+r.revision:'최초 안내'} · ${esc(r.name)} ${r.deleted?'(삭제)':''}</b><p>${esc(INHERITANCE[r.inheritance])} · ${esc(r.look)}</p><p>${esc(r.note)}</p><span class="foot-meta">${stamp(r.updatedAt)}</span><div>${btn('restore-version','이 내용으로 복원',`data-version="${i}"`)}</div></div>`).join('')||empty('변경 이력이 없습니다.')}</div>`;
 dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.querySelectorAll('[data-version]').forEach(b=>b.onclick=()=>{dialog.close();editMorph(mid,rows[+b.dataset.version]);});dialog.showModal();
}
function candidates(){return [...mine().map(g=>({...g,key:'own:'+g.id,own:true})),...state.public.filter(g=>g.ownerId!==state.user?.uid).map(g=>({...g,id:g.publicId,key:'public:'+g.publicId,own:false}))];}
function renderGenetics(){
 calcEpoch++;const list=candidates();if(!list.some(g=>g.key===choiceA))choiceA=list[0]?.key||'';if(!list.some(g=>g.key===choiceB))choiceB=list.find(g=>g.key!==choiceA)?.key||'';
 content.innerHTML=`<div class="card pad"><h2>어떤 크레를 만나게 될까요?</h2><p class="muted">내 개체와 공개된 다른 사용자의 개체를 선택하세요. 도감에서 선택한 특징으로 계산합니다. 미확인 형질은 아래 가정 옵션으로 비교할 수 있습니다.</p>${list.length>=2?`<div class="form-grid two">${select('개체 A','genA',Object.fromEntries(list.map(g=>[g.key,`${g.own?'내 개체':'공개'} · ${g.name} · ${sexLabel(g.sex)}`])),choiceA)}${select('개체 B','genB',Object.fromEntries(list.map(g=>[g.key,`${g.own?'내 개체':'공개'} · ${g.name} · ${sexLabel(g.sex)}`])),choiceB)}</div><label class="check section-gap"><input id="assumeMissing" type="checkbox" checked><span>미확인 유전자는 없음·비보인으로 가정하여 시뮬레이션<br><span class="help">실제 유전자 확인 결과가 아닙니다. 해제하면 확인된 형질만 계산합니다.</span></span></label><div class="toolbar section-gap">${btn('calculate','교배 예상하기','',true)}${btn('go-public','공개 개체 둘러보기')}${state.public.length===publicLimit?btn('more-public','공개 개체 더 불러오기'):''}</div>`:empty('계산할 개체가 2마리 이상 필요합니다.','내 개체를 등록하거나 공개된 개체를 기다려 주세요.')}<p class="inherit-note">선택한 도감 특징 중 계산 모델이 있는 릴리화이트·아잔틱·카푸치노와 헷·조합을 계산합니다. 도감의 공동 편집 내용은 계산식을 변경하지 않습니다. 솔리드백·색상·패턴은 고정 확률을 계산하지 않습니다.</p></div><div id="genResult" class="section-gap"></div>`;
 if($('#assumeMissing'))$('#assumeMissing').onchange=()=>{calcEpoch++;$('#genResult').innerHTML='';};
 for(const key of ['genA','genB']){const el=content.querySelector(`[name=${key}]`);if(el)el.onchange=()=>{choiceA=content.querySelector('[name=genA]').value;choiceB=content.querySelector('[name=genB]').value;calcEpoch++;$('#genResult').innerHTML='';};}
}
async function calculate(){
 const list=candidates();let a=list.find(g=>g.key===choiceA),b=list.find(g=>g.key===choiceB);if(!a||!b||a.key===b.key){toast('서로 다른 두 개체를 선택하세요.');return;}
 const epoch=++calcEpoch;$('#genResult').innerHTML='<p class="loading">공개 상태와 유전 정보를 확인 중…</p>';
 try{if(!a.own)a={...await store.getPublic(a.publicId),own:false};if(!b.own)b={...await store.getPublic(b.publicId),own:false};if(epoch!==calcEpoch||view!=='genetics')return;
 const result=simulateTraits(a,b,state.catalog,$('#assumeMissing')?.checked===true),unknown=result.unknown.map(k=>GENES[k]);const same=a.sex!=='unknown'&&a.sex===b.sex;const solid=result.parents.some(g=>g.genetics.solidBack==='present');
 $('#genResult').innerHTML=`<div class="result-summary"><b>${esc(a.name)} × ${esc(b.name)}</b><br>${same?'같은 성별로 등록되어 있어 실제 교배 대상은 아닙니다. ':''}${a.sex==='unknown'||b.sex==='unknown'?'성별이 미확인된 개체가 포함됩니다. ':''}${a.own&&b.own?esc(relation(a,b,mine())):'공개 개체의 비공개 혈통 정보는 확인할 수 없습니다.'}</div><p class="help">부모의 선택 특징: ${esc((a.customTraits||[]).join(' · ')||'기존 유전 기록')} × ${esc((b.customTraits||[]).join(' · ')||'기존 유전 기록')}<br>색상·무늬 및 계산 모델이 없는 모프의 출현 확률은 산정하지 않습니다.</p>${result.assumptions.length?`<div class="notice"><b>가정에 따른 시뮬레이션</b><br>${result.assumptions.map(esc).join(' · ')}<br>아래 확률은 이 가정이 맞을 때의 결과입니다. 숨은 헷이나 미확인 유전자가 있으면 달라집니다.</div>`:''}${unknown.length?`<div class="notice">${esc(unknown.join(' · '))} 은 미확인입니다. ${result.rows.length?'확인된 형질의 결과를 아래에 표시합니다.':'도감에서 특징을 선택하거나 가정 옵션을 켜서 시뮬레이션하세요.'}</div>`:''}${result.rows.some(r=>r.genes.lilly===2)?'<p class="notice danger">슈퍼 릴리 가능성이 포함됩니다. 치사 위험이 있어 릴리끼리의 실제 교배는 권장하지 않습니다.</p>':''}${result.rows.some(r=>r.genes.cappuccino===2)?'<p class="notice">슈퍼 카푸치노 가능성이 포함되며 건강 문제 보고가 있습니다.</p>':''}${result.rows.length?`<div class="card section-gap"><div class="table-wrap"><table><thead><tr><th>${result.assumptions.length?'가정 시 확률':'확인된 형질 확률'}</th><th>예상 모프 · 유전 상태</th><th>표현 특징</th></tr></thead><tbody>${result.rows.map(r=>`<tr><td><b>${pct(r.p)}</b></td><td>${esc(offspringName(r.genes))}</td><td>${solid?'솔리드백은 표현 가능성만 안내':'색상·패턴의 고정 확률 미산정'}</td></tr>`).join('')}</tbody></table></div></div>`:''}`;
 }catch(e){if(epoch===calcEpoch&&view==='genetics')$('#genResult').innerHTML=`<div class="notice">${esc(store.friendlyError(e))}</div>`;}
}
function editNickname(){
 if(!requireUser())return;const epoch=authEpoch;
 openForm('닉네임 설정',`${field('닉네임','nickname',profiles.get(state.user.uid)?.nickname||'','text','required minlength="2" maxlength="20" autocomplete="off"')}<p class="help">2~20자로 입력하세요. 공개 개체에 주인 닉네임으로 표시됩니다. 구글 계정 이름과 이메일은 공개하지 않습니다. 닉네임은 중복될 수 있습니다.</p>`,async data=>{
  if(epoch!==authEpoch)throw Error('로그인 계정이 변경되었습니다.');await store.saveNickname(data.get('nickname'));
 });
}
function syncProfiles(){
 const ids=new Set(state.public.map(g=>g.ownerId).filter(Boolean));if(state.user)ids.add(state.user.uid);
 for(const [uid,stop] of profileStops)if(!ids.has(uid)){stop();profileStops.delete(uid);profiles.delete(uid);}
 for(const uid of ids)if(!profileStops.has(uid)){
  const stop=store.watchProfile(uid,profile=>{
   profiles.set(uid,profile);authUI();if(uid===state.user?.uid&&view==='chat'&&$('#chatIdentity'))$('#chatIdentity').textContent='대화 이름: '+ownerNickname(uid);
   document.querySelectorAll('[data-owner-id]').forEach(el=>{if(el.dataset.ownerId===uid)el.textContent='주인 · '+ownerNickname(uid);});
   if(uid===state.user?.uid&&!profile?.nickname&&!nicknamePrompted&&!dialog.open){nicknamePrompted=true;editNickname();}
  },()=>{if(uid===state.user?.uid)notice('닉네임 연결에 필요한 최신 Firestore 규칙을 게시해 주세요. 기존 개체 기록은 유지됩니다.');});
  profileStops.set(uid,stop);
 }
}
async function detailPublic(pid){const g=await store.getPublic(pid);dialog.innerHTML=`<div class="modal-card"><div class="modal-head"><div><h2>${esc(g.name)}</h2><p>${esc(g.morph)} · ${sexLabel(g.sex)}</p></div><button type="button" class="icon-btn" data-close aria-label="닫기">×</button></div><div class="detail-photos">${g.photos.map(p=>`<img src="${esc(p)}" alt="${esc(g.name)} 사진">`).join('')}</div><p class="owner-nickname" data-owner-id="${esc(g.ownerId)}">주인 · ${esc(ownerNickname(g.ownerId))}</p><p>부화일: ${esc(fmt(g.hatchDate))}</p><div class="tag-line">${g.customTraits.map(t=>`<span class="morph-tag">${esc(t)}</span>`).join('')}</div><p class="help">개인 메모와 성장·혈통 기록은 공개하지 않습니다.</p>${state.user?.uid!==g.ownerId?btn('dm-public','주인과 대화',`data-id="${esc(pid)}"`):''}${btn('use-genetics','이 개체로 교배 예상',`data-id="public:${pid}"`,true)}</div>`;dialog.querySelector('[data-close]').onclick=()=>dialog.close();const dm=dialog.querySelector('[data-action=dm-public]');if(dm)dm.onclick=()=>startPrivate(pid).catch(e=>toast(store.friendlyError(e)));dialog.querySelector('[data-action=use-genetics]').onclick=()=>{dialog.close();choiceA='public:'+pid;setView('genetics');};dialog.showModal();}
async function remove(kind,rid){const record=state[kind].find(r=>r.id===rid);if(record&&confirm('이 기록을 삭제할까요?')){await store.removeRecord(kind,record);toast('기록을 삭제했습니다.');}}
function subscribePublic(){if(stopPublic)stopPublic();stopPublic=store.watchPublic(rows=>{state.public=rows;syncProfiles();if(['geckos','genetics','dashboard'].includes(view))onData();},err=>notice('공개 개체 연결 오류: '+store.friendlyError(err)),publicLimit);}
function renderChat(){if(!state.ready){content.innerHTML=empty('채팅 서버 연결을 기다려 주세요.');return;}if(!chatCleanup)chatCleanup=mountChat(content,store,{roomId:chatRoom,onNickname:editNickname});}
async function startPrivate(pid){if(!requireUser())return;const epoch=authEpoch;const room=await store.openPrivateRoom(pid);if(epoch!==authEpoch)return;if(dialog.open)dialog.close();chatCleanup?.();chatCleanup=null;chatRoom=room;setView('chat');}
const actions={'dm-public':startPrivate,nickname:()=>editNickname(),'import-legacy':()=>{if(requireUser())openLegacyImport({dialog,store,compress,onDone:render});},'more-public':()=>{publicLimit+=200;subscribePublic();},login:async()=>{if(!state.ready)throw Error('Google 로그인과 저장은 Firebase 연결 후 사용할 수 있습니다.');await store.login();},logout:async()=>{if(dialog.open)dialog.close();await store.logout();},'go-public':()=>{tab='public';setView('geckos');},'go-morphs':()=>setView('morphs'),'go-genetics':()=>setView('genetics'),mine:()=>{tab='mine';renderGeckos();},public:()=>{tab='public';renderGeckos();},'add-gecko':()=>editGecko(),'edit-gecko':k=>editGecko(k),'add-growth':()=>editGrowth(),'edit-growth':k=>editGrowth(k),'delete-growth':k=>remove('growth',k),'add-pair':()=>editPair(),'edit-pair':k=>editPair(k),'delete-pair':k=>remove('pairings',k),'add-morph':()=>editMorph(),'edit-morph':k=>editMorph(k),'delete-morph':k=>deleteMorph(k),'history-morph':k=>showHistory(k),'detail-public':k=>detailPublic(k),'use-genetics':k=>{choiceA=k;setView('genetics');},calculate};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
for(const root of [content,$('#authArea')])root.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||!actions[b.dataset.action])return;b.disabled=true;try{await actions[b.dataset.action](b.dataset.id);}catch(err){toast(store.friendlyError(err));}finally{b.disabled=false;}});
function notice(text){$('#connectionNotice').textContent=text;$('#connectionNotice').hidden=!text;}
function onData(){if(view==='genetics')calcEpoch++;render();}
authUI();render();
if(!store.configured)notice('아직 서비스 연결 전입니다. 모프 도감은 둘러볼 수 있으며, 로그인·공용 저장은 서비스 연결 후 활성화됩니다.');
else{
 try{await store.connect();state.ready=true;
 store.watchCatalog(rows=>{state.catalog=mergeCatalog(SEED,rows);if(view==='morphs')renderMorphs();},err=>notice('모프 도감 연결 오류: '+store.friendlyError(err)));
 subscribePublic();
 store.watchAuth(user=>{
  if(chatUid!==(user?.uid||null)){chatUid=user?.uid||null;chatCleanup?.();chatCleanup=null;chatRoom='';if(view==='chat')render();}
  if(!user)store.ensureVisitor().catch(()=>{});
  else if(user.isAnonymous)store.ensureVisitor().catch(()=>{});
  const next=user&&!user.isAnonymous?user:null;if((state.user?.uid||null)===(next?.uid||null)){authUI();return;}
  nicknamePrompted=false;authEpoch++;calcEpoch++;unsub.forEach(fn=>fn());unsub=[];state.user=next;state.geckos=[];state.growth=[];state.pairings=[];state.ownLoaded=false;growthFocus='';choiceA='';choiceB='';if(dialog.open)dialog.close();authUI();render();syncProfiles();
  if(next){let loaded=new Set();const epoch=authEpoch;for(const kind of ['geckos','growth','pairings'])unsub.push(store.watchOwn(kind,rows=>{if(epoch!==authEpoch)return;state[kind]=rows;loaded.add(kind);state.ownLoaded=loaded.size===3;onData();},err=>notice('내 기록 연결 오류: '+store.friendlyError(err))));}
 });
 }catch(err){notice('서비스 연결에 실패했습니다: '+store.friendlyError(err));}
}
