import {esc} from './core.mjs';
export function mountChat(root,store,{roomId='',onNickname=()=>{}}={}){
 let disposed=false,current=roomId,mode=roomId?'private':'public',rooms=[],messageStop=null,roomStop=null,count=50,epoch=0;
 const names=new Map(),profileStops=new Map();
 root.innerHTML=`<div class="community-tabs"><button class="btn secondary" id="chatPublic">공용 채팅방</button><button class="btn secondary" id="chatPrivate">개인 대화</button></div><p class="help">공용 채팅은 누구나 읽을 수 있습니다. 게스트 번호는 서버에서 첫 접속을 등록한 순서대로 발급하며, 브라우저 세션이 바뀌면 새 번호를 받을 수 있습니다. 개인 대화는 로그인한 두 사람만 읽을 수 있습니다.</p><div class="chat-layout"><aside class="card chat-rooms" id="chatRooms"></aside><section class="card chat-main"><h2 id="chatTitle"></h2><p id="chatIdentity" class="help"></p><button class="btn secondary small" id="chatMore">이전 메시지 더 보기</button><div id="chatMessages" class="chat-messages" role="log" aria-label="채팅 메시지" aria-live="polite"></div><form id="chatForm"><label for="chatText">메시지</label><textarea id="chatText" maxlength="1000" rows="3" placeholder="메시지를 입력하세요"></textarea><div class="toolbar"><button class="btn primary" type="submit">보내기</button><button class="btn secondary" type="button" id="chatNickname">닉네임 설정</button></div></form><p id="chatError" role="alert" class="form-error"></p></section></div>`;
 const q=s=>root.querySelector(s),fail=e=>{if(!disposed)q('#chatError').textContent=store.friendlyError(e);};
 const uid=store.chatUser()?.uid,google=!!store.chatUser()&&!store.chatUser().isAnonymous;
 function other(room){return room.members.find(id=>id!==uid);}
 function roomName(room){return names.get(other(room))||'닉네임 미설정';}
 function paintRooms(){if(disposed)return;q('#chatRooms').hidden=mode!=='private';q('#chatRooms').innerHTML=google?(rooms.map(r=>`<button type="button" class="chat-room" data-room="${esc(r.id)}" aria-pressed="${current===r.id}">${esc(roomName(r))} 님과 대화</button>`).join('')||'<p>공개 개체의 ‘주인과 대화’ 버튼으로 대화를 시작하세요.</p>'):'<p>개인 대화는 상단에서 Google 로그인 후 사용할 수 있습니다.</p>';q('#chatRooms').querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>select('private',b.dataset.room));if(mode==='private'&&current)q('#chatTitle').textContent=(rooms.find(r=>r.id===current)?roomName(rooms.find(r=>r.id===current)):'상대방')+' 님과 1대1 대화';}
 function listen(){if(messageStop)messageStop();messageStop=null;const token=++epoch;q('#chatMessages').innerHTML='';q('#chatForm').hidden=mode==='private'&&(!google||!current);q('#chatMore').hidden=q('#chatForm').hidden;if(q('#chatForm').hidden)return;
 messageStop=store.watchMessages(current,rows=>{if(disposed||token!==epoch)return;const box=q('#chatMessages'),nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<100,previousHeight=box.scrollHeight,first=!box.children.length;
 box.innerHTML=rows.map(m=>`<article class="chat-message ${m.senderId===uid?'chat-mine':''}"><header><b>${esc(m.senderName)}</b><time>${m.createdAt?.toDate?esc(m.createdAt.toDate().toLocaleString('ko-KR')):'전송 중'}</time></header><p>${esc(m.text)}</p></article>`).join('')||'<p class="help">아직 메시지가 없습니다. 첫 대화를 시작해 보세요.</p>';q('#chatMore').hidden=rows.length<count;if(nearBottom||first)box.scrollTop=box.scrollHeight;else box.scrollTop+=box.scrollHeight-previousHeight;
 },fail,count);}
 function select(next,id=''){mode=next;current=id;count=50;q('#chatText').value='';q('#chatError').textContent='';q('#chatTitle').textContent=mode==='public'?'함께 이야기해요':'개인 대화를 선택하세요';q('#chatPublic').setAttribute('aria-pressed',String(mode==='public'));q('#chatPrivate').setAttribute('aria-pressed',String(mode==='private'));paintRooms();listen();}
 q('#chatPublic').onclick=()=>select('public');q('#chatPrivate').onclick=()=>select('private',rooms[0]?.id||'');q('#chatMore').onclick=()=>{count+=50;listen();};q('#chatNickname').hidden=!google;q('#chatNickname').onclick=onNickname;
 q('#chatForm').onsubmit=async e=>{e.preventDefault();const button=q('[type=submit]'),input=q('#chatText'),text=input.value,room=current;button.disabled=true;q('#chatError').textContent='';try{await store.sendChat(room,text);if(!disposed&&input.value===text&&current===room)input.value='';}catch(error){fail(error);}finally{if(!disposed)button.disabled=false;}};
 if(google)roomStop=store.watchRooms(rows=>{if(disposed)return;rooms=rows;for(const room of rooms){const id=other(room);if(!profileStops.has(id))profileStops.set(id,store.watchProfile(id,p=>{names.set(id,p?.nickname||'닉네임 미설정');paintRooms();},fail));}paintRooms();},fail);
 store.chatIdentity().then(identity=>{if(!disposed)q('#chatIdentity').textContent='대화 이름: '+identity.name;}).catch(fail);
 select(mode,current);
 return ()=>{disposed=true;epoch++;messageStop?.();roomStop?.();profileStops.forEach(stop=>stop());root.innerHTML='';};
}
